name: Generate ASCII art

on: push

jobs:

  job_1:

    runs-on: ubuntu-latest
    
    steps:

      - name: Use Github's "Checkout" action
        uses: actions/checkout@v7
      
      - name: run the shell script to generate ASCII art
        run: bash ascii-gen.sh